[env:esp32doit-devkit-v1] ; (Nama board lu mungkin beda, biarin aja aslinya)
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200

lib_deps =
  marcoschwartz/LiquidCrystal_I2C
  adafruit/Adafruit ADS1X15
  adafruit/RTClib
  paulstoffregen/OneWire
  milesburton/DallasTemperature
  bblanchon/ArduinoJson@^7.0.4