[env:esp32doit-devkit-v1] ; (Ini biasanya sudah ada, biarkan saja)
platform = espressif32 ; (Contoh jika pakai ESP32)
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200

; Tambahkan bagian ini di bawahnya:
lib_deps =
  marcoschwartz/LiquidCrystal_I2C
  adafruit/Adafruit ADS1X15
  adafruit/RTClib
  paulstoffregen/OneWire
  milesburton/DallasTemperature